#FSR Autogenerated Content. DO NOT DELETE
from .extract_data_from_csv import *
 
supported_operations = {'extract_data_from_csv': extract_data_from_csv, 'extract_data_from_two_csv': extract_data_from_two_csv }