#FSR Autogenerated Content. DO NOT DELETE
from .extract_data_from_csv import *
 
supported_operations = {'extract_data_from_csv': extract_data_from_csv, 'merge_two_csv_and_extract_data': merge_two_csv_and_extract_data }